<?php

namespace Database\Seeders;

use App\Models\Term;
use App\Models\TermMeta;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TermSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $terms = [
            ['id' => '1','title' => 'From A Small Startup To A Leading Global Agency In 15 Years','slug' => 'from-a-small-startup-to-a-leading-global-agency-in-15-years-1','type' => 'blog','status' => '1','featured' => '1','lang' => 'en','comment_status' => '1','meta' => NULL,'created_at' => '2022-06-28 08:15:00','updated_at' => '2022-06-28 08:15:00'],
            ['id' => '4','title' => 'From A Small Startup To A Leading Global Agency In 15 Years','slug' => 'from-a-small-startup-to-a-leading-global-agency-in-15-years-2','type' => 'blog','status' => '1','featured' => '1','lang' => 'en','comment_status' => '1','meta' => NULL,'created_at' => '2022-06-28 08:15:51','updated_at' => '2022-06-28 08:15:51'],
            ['id' => '5','title' => 'From A Small Startup To A Leading Global Agency In 15 Years','slug' => 'from-a-small-startup-to-a-leading-global-agency-in-15-years-3','type' => 'blog','status' => '1','featured' => '1','lang' => 'en','comment_status' => '1','meta' => NULL,'created_at' => '2022-06-28 08:16:23','updated_at' => '2022-06-28 08:16:23'],
            ['id' => '2','title' => 'From A Small Startup To A Leading Global Agency In 15 Years','slug' => 'from-a-small-startup-to-a-leading-global-agency-in-15-years-4','type' => 'blog','status' => '1','featured' => '1','lang' => 'en','comment_status' => '1','meta' => NULL,'created_at' => '2022-06-28 08:16:23','updated_at' => '2022-06-28 08:16:23'],
            ['id' => '3','title' => 'From A Small Startup To A Leading Global Agency In 15 Years','slug' => 'from-a-small-startup-to-a-leading-global-agency-in-15-years-5','type' => 'blog','status' => '1','featured' => '1','lang' => 'en','comment_status' => '1','meta' => NULL,'created_at' => '2022-06-28 08:15:00','updated_at' => '2022-06-28 08:15:00'],
            ['id' => '6','title' => 'From A Small Startup To A Leading Global Agency In 15 Years','slug' => 'from-a-small-startup-to-a-leading-global-agency-in-15-years-6','type' => 'blog','status' => '1','featured' => '1','lang' => 'en','comment_status' => '1','meta' => NULL,'created_at' => '2022-06-28 08:15:51','updated_at' => '2022-06-28 08:15:51']
        ];

        Term::insert($terms);

        $term_metas = [
            ['id' => '1','term_id' => '1','key' => 'excerpt','value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iusto debitis doloremque nulla reiciendis illum.'],
            ['id' => '2','term_id' => '1','key' => 'metatag','value' => 'Business, Design, Software'],
            ['id' => '3','term_id' => '1','key' => 'metadescription','value' => NULL],
            ['id' => '4','term_id' => '1','key' => 'preview','value' => '/uploads/1/22/06/62b9a17e9e1652706221656332670.jpg'],
            ['id' => '5','term_id' => '1','key' => 'description','value' => '<p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">Dolor sit amet consectetur adipisicing elit. Eligendi ab illo ad incidunt unde cumque magnam iure numquam sed dicta voluptatum corrupti nulla non culpa vitae velit, quae autem facilis nam in. Debitis recusandae ratione molestiae facere voluptatibus quo ipsum modi sapiente incidunt minima, reprehenderit, id harum sequi illo eius? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas odio, recusandae sequi consequatur illo debitis porro quos vitae adipisci deleniti voluptatem magnam, dolores, ipsa reiciendis?</p><h6 style="margin: 30px 0px 15px; padding: 0px; line-height: 1.3; font-size: 20px; font-family: Chivo, sans-serif; color: rgb(34, 34, 34);">Execution is the single biggest factor in achievement.</h6><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success.</p><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur velit inventore et nesciunt molestias sunt, eligendi laborum corporis cumque consectetur suscipit. Ipsum eum veniam, a quae nesciunt optio deserunt laudantium.</p>'],
            ['id' => '6','term_id' => '2','key' => 'excerpt','value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iusto debitis doloremque nulla reiciendis illum.'],
            ['id' => '7','term_id' => '2','key' => 'metatag','value' => 'Business, Design, Software'],
            ['id' => '8','term_id' => '2','key' => 'metadescription','value' => NULL],
            ['id' => '9','term_id' => '2','key' => 'preview','value' => '/uploads/1/22/06/62b9a17ef277f2706221656332670.jpg'],
            ['id' => '10','term_id' => '2','key' => 'description','value' => '<p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">Dolor sit amet consectetur adipisicing elit. Eligendi ab illo ad incidunt unde cumque magnam iure numquam sed dicta voluptatum corrupti nulla non culpa vitae velit, quae autem facilis nam in. Debitis recusandae ratione molestiae facere voluptatibus quo ipsum modi sapiente incidunt minima, reprehenderit, id harum sequi illo eius? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas odio, recusandae sequi consequatur illo debitis porro quos vitae adipisci deleniti voluptatem magnam, dolores, ipsa reiciendis?</p><h6 style="margin: 30px 0px 15px; padding: 0px; line-height: 1.3; font-size: 20px; font-family: Chivo, sans-serif; color: rgb(34, 34, 34);">Execution is the single biggest factor in achievement.</h6><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success.</p><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur velit inventore et nesciunt molestias sunt, eligendi laborum corporis cumque consectetur suscipit. Ipsum eum veniam, a quae nesciunt optio deserunt laudantium.</p>'],
            ['id' => '11','term_id' => '3','key' => 'excerpt','value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iusto debitis doloremque nulla reiciendis illum.'],
            ['id' => '12','term_id' => '3','key' => 'metatag','value' => NULL],
            ['id' => '13','term_id' => '3','key' => 'metadescription','value' => NULL],
            ['id' => '14','term_id' => '3','key' => 'preview','value' => '/uploads/1/22/06/62b9a17f47ac22706221656332671.jpg'],
            ['id' => '15','term_id' => '3','key' => 'description','value' => '<p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">Dolor sit amet consectetur adipisicing elit. Eligendi ab illo ad incidunt unde cumque magnam iure numquam sed dicta voluptatum corrupti nulla non culpa vitae velit, quae autem facilis nam in. Debitis recusandae ratione molestiae facere voluptatibus quo ipsum modi sapiente incidunt minima, reprehenderit, id harum sequi illo eius? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas odio, recusandae sequi consequatur illo debitis porro quos vitae adipisci deleniti voluptatem magnam, dolores, ipsa reiciendis?</p><h6 style="margin: 30px 0px 15px; padding: 0px; line-height: 1.3; font-size: 20px; font-family: Chivo, sans-serif; color: rgb(34, 34, 34);">Execution is the single biggest factor in achievement.</h6><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success.</p><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur velit inventore et nesciunt molestias sunt, eligendi laborum corporis cumque consectetur suscipit. Ipsum eum veniam, a quae nesciunt optio deserunt laudantium.</p>'],
            ['id' => '16','term_id' => '5','key' => 'excerpt','value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iusto debitis doloremque nulla reiciendis illum.'],
            ['id' => '17','term_id' => '5','key' => 'metatag','value' => 'Business, Design, Software'],
            ['id' => '18','term_id' => '5','key' => 'metadescription','value' => NULL],
            ['id' => '19','term_id' => '5','key' => 'preview','value' => '/uploads/1/22/06/62b9a17e9e1652706221656332670.jpg'],
            ['id' => '20','term_id' => '5','key' => 'description','value' => '<p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">Dolor sit amet consectetur adipisicing elit. Eligendi ab illo ad incidunt unde cumque magnam iure numquam sed dicta voluptatum corrupti nulla non culpa vitae velit, quae autem facilis nam in. Debitis recusandae ratione molestiae facere voluptatibus quo ipsum modi sapiente incidunt minima, reprehenderit, id harum sequi illo eius? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas odio, recusandae sequi consequatur illo debitis porro quos vitae adipisci deleniti voluptatem magnam, dolores, ipsa reiciendis?</p><h6 style="margin: 30px 0px 15px; padding: 0px; line-height: 1.3; font-size: 20px; font-family: Chivo, sans-serif; color: rgb(34, 34, 34);">Execution is the single biggest factor in achievement.</h6><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success.</p><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur velit inventore et nesciunt molestias sunt, eligendi laborum corporis cumque consectetur suscipit. Ipsum eum veniam, a quae nesciunt optio deserunt laudantium.</p>'],
            ['id' => '21','term_id' => '6','key' => 'excerpt','value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iusto debitis doloremque nulla reiciendis illum.'],
            ['id' => '22','term_id' => '6','key' => 'metatag','value' => 'Business, Design, Software'],
            ['id' => '23','term_id' => '6','key' => 'metadescription','value' => NULL],
            ['id' => '24','term_id' => '6','key' => 'preview','value' => '/uploads/1/22/06/62b9a17ef277f2706221656332670.jpg'],
            ['id' => '25','term_id' => '6','key' => 'description','value' => '<p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">Dolor sit amet consectetur adipisicing elit. Eligendi ab illo ad incidunt unde cumque magnam iure numquam sed dicta voluptatum corrupti nulla non culpa vitae velit, quae autem facilis nam in. Debitis recusandae ratione molestiae facere voluptatibus quo ipsum modi sapiente incidunt minima, reprehenderit, id harum sequi illo eius? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas odio, recusandae sequi consequatur illo debitis porro quos vitae adipisci deleniti voluptatem magnam, dolores, ipsa reiciendis?</p><h6 style="margin: 30px 0px 15px; padding: 0px; line-height: 1.3; font-size: 20px; font-family: Chivo, sans-serif; color: rgb(34, 34, 34);">Execution is the single biggest factor in achievement.</h6><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success.</p><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur velit inventore et nesciunt molestias sunt, eligendi laborum corporis cumque consectetur suscipit. Ipsum eum veniam, a quae nesciunt optio deserunt laudantium.</p>'],
            ['id' => '26','term_id' => '4','key' => 'excerpt','value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iusto debitis doloremque nulla reiciendis illum.'],
            ['id' => '27','term_id' => '4','key' => 'metatag','value' => NULL],
            ['id' => '28','term_id' => '4','key' => 'metadescription','value' => NULL],
            ['id' => '29','term_id' => '4','key' => 'preview','value' => '/uploads/1/22/06/62b9a17f47ac22706221656332671.jpg'],
            ['id' => '30','term_id' => '4','key' => 'description','value' => '<p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">Dolor sit amet consectetur adipisicing elit. Eligendi ab illo ad incidunt unde cumque magnam iure numquam sed dicta voluptatum corrupti nulla non culpa vitae velit, quae autem facilis nam in. Debitis recusandae ratione molestiae facere voluptatibus quo ipsum modi sapiente incidunt minima, reprehenderit, id harum sequi illo eius? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas odio, recusandae sequi consequatur illo debitis porro quos vitae adipisci deleniti voluptatem magnam, dolores, ipsa reiciendis?</p><h6 style="margin: 30px 0px 15px; padding: 0px; line-height: 1.3; font-size: 20px; font-family: Chivo, sans-serif; color: rgb(34, 34, 34);">Execution is the single biggest factor in achievement.</h6><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success.</p><p style="margin-right: 0px; margin-left: 0px; padding: 0px; line-height: 1.7; color: rgb(33, 37, 41); font-size: 17px; font-family: &quot;Noto Sans&quot;, sans-serif;">The price is something not necessarily defined as financial. It could be time, effort, sacrifice, money or perhaps, something else. The point is that we must be fully aware of the price and be willing to pay it, if we want to have success. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur velit inventore et nesciunt molestias sunt, eligendi laborum corporis cumque consectetur suscipit. Ipsum eum veniam, a quae nesciunt optio deserunt laudantium.</p>']
        ];

        TermMeta::insert($term_metas);

    }
}
